In [1]:
#Numpy: Numpy is number python (this is library)
import numpy as np

In [2]:
np.sqrt(10)

3.1622776601683795

In [3]:
print('Minimum' , np.amin([12,15,42,15,5,16]))
print('Maximum', np.amax([12,15,42,15,5,16]))

Minimum 5
Maximum 42


In [4]:
#rounded off to next number
np.ceil(29.4)

30.0

In [5]:
np.ceil(29.6)

30.0

In [6]:
np.ceil(np.sqrt(10))

4.0

In [7]:
np.ceil(np.sum(np.sqrt([5,15,10])))

10.0

In [8]:
np.sqrt(5)

2.23606797749979

In [9]:
np.sqrt(15)

3.872983346207417

In [10]:
np.sum(np.sqrt([5,10,15]))

9.271328983875588

In [11]:
print(dir(Numpy))

NameError: name 'Numpy' is not defined

In [12]:
print(dir(numpy))

NameError: name 'numpy' is not defined

In [13]:
import numpy
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [14]:
#we need data in form of array
np.array([5,10,15])

array([ 5, 10, 15])

In [15]:
type([5,10,15])

list

In [16]:
#two dimensions
a= np.array([[1,2],[3,4],[5,6]])
print("Type- ",a.dtype)
print('\n','*' *30)  # \n forthe next line
print('\n',a)

Type-  int32

 ******************************

 [[1 2]
 [3 4]
 [5 6]]


In [17]:
#dtype conversion
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [19]:
#creating array using .mat using
np.array(np.mat('1,2,3 ; 4,5,6'))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#convert a list into an array
a= [1,2]
c = np.array(a)
print(c,type(c))


[1 2] <class 'numpy.ndarray'>


In [23]:
#copy array into other
b = np.array(c)
print(b)

[1 2]


In [24]:
# data types
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix \n------------------\n", mat, "\n-----------------")
print("Dimension of this matrix: ", mat.ndim, sep='') #dim gives the dimensions, 2 for matrix and 1 for vector
print("size of this matrix: ",mat.size,sep='') #Size gives the total number of elements
print("Shape of this matrix: ",mat.shape) #shape gives the number of element along each axes (dimensions)
print("Data type of this matrix:",mat.dtype) #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix 
------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------------
Dimension of this matrix: 2
size of this matrix: 9
Shape of this matrix:  (3, 3)
Data type of this matrix: int32


In [25]:
#arange and linspace
#dont work with python
list(range(2,10.5,4.5))

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
a= np.arange(2,10.5,.5)
print(a)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10. ]


In [28]:
#reverse order
a[::-1]

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ])

In [29]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,0,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [30]:
print("Linearly spaced numbers between 1 and 5\n------------------------------")
print(np.linspace(10,40,5)) #here 5 is 5 numbers in between 10 to 40

Linearly spaced numbers between 1 and 5
------------------------------
[10.  17.5 25.  32.5 40. ]


In [31]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


In [32]:
#include end point and check space between the points
#by defaults endpoint = True
#by defaults retstep =False
np.linspace(2.0,3.0,num=4,endpoint=False,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [34]:
#Matrix Creation
print("Vector of Zeros \n--------------------")
print(np.zeros(5))

Vector of Zeros 
--------------------
[0. 0. 0. 0. 0.]


In [35]:
print("Matrix of zeros \n---------------")
print(np.zeros((5,6))) #Notice Tuple

Matrix of zeros 
---------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [36]:
print("Metrix of Ones\n------------------")
print(np.ones((5,8)))

Metrix of Ones
------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
print("Matrix of 5's \n------------------")
print(5*np.ones((2,3)))

Matrix of 5's 
------------------
[[5. 5. 5.]
 [5. 5. 5.]]


In [42]:
#Cnstruct diagonal matrix
x= np.arange(30).reshape(5,6)  #reshape is making a matix
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [43]:
#Random number Generation
import numpy as np

In [45]:
np.random.seed(6) #Each seed number will generate similar data
print("Random number generation (from unifom distribution)")
print(np.random.rand(10,6))

Random number generation (from unifom distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [46]:
print("numbers from normal distribution with zero mean and standard deviation 1 i.e standard normal")
print(np.random.randn(10,3))

numbers from normal distribution with zero mean and standard deviation 1 i.e standard normal
[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [48]:
print("Random integer vector: ",np.random.randint(5,20,10)) #randint (low,hingh, # of samples to be drawn)

Random integer vector:  [12 12 16 10  8 13 12  8 15 10]


In [49]:
print("\n Random integer matrix")
print(np.random.randint(1,30,(6,7))) #randint( low,high, # of sample to be shown in a tuple to from a matix)


 Random integer matrix
[[26  4 25  1 24 29 24]
 [14 17  4  6  4 14  3]
 [13  4 15 21 26  1  9]
 [ 7  4 19  2 23  9 25]
 [10  1  8 23 17 18  9]
 [ 6 15 26 13 25 14  6]]


In [50]:
#Numpy condition
emp_salary = np.random.randint(8,70,10)
emp_salary

array([17, 68,  9, 52,  9, 58, 33, 33, 45, 35])

In [51]:
#set minimum and maximum salary using a_min and a_max
np.clip(emp_salary,a_min=20,a_max=50)

array([20, 50, 20, 50, 20, 50, 33, 33, 45, 35])

In [52]:
#if yo want to find actual salary which are less than of greater than some salary use np.where
#np.where gives index details
print(np.where(emp_salary<20))

(array([0, 2, 4], dtype=int64),)


In [53]:
#if you want to see actual data use index
emp_salary[[1,3,7,8]]

array([68, 52, 33, 45])