In [1]:
import numpy as np
from numpy.random import randint as ri
a = ri(1,99,30)
a

array([76, 60,  2,  5, 62, 55, 16, 48, 26, 22, 29, 75, 65, 11,  6, 96, 80,
       93, 31, 88, 96, 74, 47, 29, 19,  3,  7, 80, 78, 27])

In [2]:
b= a.reshape(2,3,5)  # 2 is here for 2 matrix 
b

array([[[76, 60,  2,  5, 62],
        [55, 16, 48, 26, 22],
        [29, 75, 65, 11,  6]],

       [[96, 80, 93, 31, 88],
        [96, 74, 47, 29, 19],
        [ 3,  7, 80, 78, 27]]])

In [3]:
c= a.reshape(6,5)
c

array([[76, 60,  2,  5, 62],
       [55, 16, 48, 26, 22],
       [29, 75, 65, 11,  6],
       [96, 80, 93, 31, 88],
       [96, 74, 47, 29, 19],
       [ 3,  7, 80, 78, 27]])

In [4]:
print("min of a: ", c.min())
print("max of b: ", c.max())

min of a:  2
max of b:  96


In [5]:
#sorting
m = ri(1,100,25).reshape(5,5)
print("\n matrix of random integers\n",'-'*50,'\n',m)
print('\n Here is the sorted matrix along each row\n','-'*50,'\n',np.sort(m)) #default axis =1
print('\n Here is the sorted matrix along each column\n','-'*50,'\n',np.sort(m,axis=0))


 matrix of random integers
 -------------------------------------------------- 
 [[30 86 82 88 81]
 [95 84  5 53 78]
 [52 75 83 40 24]
 [ 1 14 29 10 77]
 [70 62 13 10 55]]

 Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[30 81 82 86 88]
 [ 5 53 78 84 95]
 [24 40 52 75 83]
 [ 1 10 14 29 77]
 [10 13 55 62 70]]

 Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 1 14  5 10 24]
 [30 62 13 10 55]
 [52 75 29 40 77]
 [70 84 82 53 78]
 [95 86 83 88 81]]


In [6]:
#indexing and slicing
arr= np.arange(13,30)
print("Array: ",arr)

Array:  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [7]:
print("Element at 7th index is: ",arr[7])

Element at 7th index is:  20


In [8]:
print('Element from 3rd to 5th index are: ',arr[3:6])

Element from 3rd to 5th index are:  [16 17 18]


In [9]:
#subseting
mat = np.array(ri(10,100,15)).reshape(3,5)
print(mat)

[[97 63 60 83 79]
 [66 45 74 57 37]
 [64 29 55 71 54]]


In [12]:
xyz =mat[mat>70]

In [13]:
xyz

array([97, 83, 79, 74, 71])

In [14]:
print(np.where(mat==71))

(array([2], dtype=int64), array([3], dtype=int64))


In [15]:
#univeral functions
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print(mat2)

[[8 5 2]
 [8 2 7]
 [9 9 9]]
[[2 4 8]
 [4 2 5]
 [7 8 6]]


In [16]:
print(mat1+mat2)

[[10  9 10]
 [12  4 12]
 [16 17 15]]


In [17]:
print(mat1*mat2)

[[16 20 16]
 [32  4 35]
 [63 72 54]]


In [18]:
#Broadcasting
#calculation in differect sizes of matrixs